name: Deploy Next.js to Infomaniak

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        # Note : Assurez-vous que votre next.config.ts contient : output: 'export'

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Infomaniak via Rsync
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -p 22" ./out/ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:web/



